### ISSUE TITLE
Distribution of topics for each documents

### ISSUE THREAD

**Issue by APavlides** [bachtranxuan/GCTM#1]
Thanks for your work on this, the integration of a KG is really interesting. I am not an expert in topic models but have been reading the paper carefully for a couple of days. There is one thing I would like to be able to do but I am not sure how. I see in the output files that there is the distribution of words for each topic, but how do I get the distribution of topics for each document? It would be great if you, or myself (I will give it a go), could add another file to the output per minibatch with the topic distribution of each document. Looking at the paper, I think this is stored in the variable theta_d, but in the code this is not accessible directly but is part of the calculation of gamma_d. Should I be outputting gamma_d instead of theta_d perhaps? Your help would be much appreciated. Best regards, Alex

**Comment by linhngovanbk** [comment]
Thank you for your attention to our work.
We use the variational inference method to approximate the true posterior $p(\theta_d|w_d,\alpha,\beta)$ by the variational distribution $q(\theta_d|\gamma_d)$. This variational distribution is Dirichlet and $\gamma_d$ is the hyperparameter. Therefore, you can sample $\theta_d$ from the variational distribution. Or, you can use the mean of this distribution to generate $\theta_d$, it means that $E[\theta_d] = norm(gamma_d)$.

Best regards, Linh
